
import React from 'react';
import { 
  Info, 
  Bot, 
  ShieldOff, 
  Hospital, 
  User, 
  Shield, 
  Copyright, 
  FileText, 
  Settings, 
  Ban,
  RefreshCw, 
  Mail
} from 'lucide-react';
import { Card, CardContent } from '@/components/ui/card';
import { cn } from '@/lib/utils';

const TermsAndConditions: React.FC = () => {
  return (
    <div className="container mx-auto px-4 py-12">
      <div className="max-w-4xl mx-auto">
        <h1 className="text-4xl font-serif font-bold mb-8 text-earth-900 text-center">
          Terms <span className="text-spirit-600">&</span> Conditions
        </h1>
        
        <Card className="mb-8 border-spirit-200 bg-earth-50/50">
          <CardContent className="pt-6">
            <p className="text-earth-800 text-lg">
              Welcome to Flow 83. By accessing and using this platform, you agree to the following terms and conditions. 
              Please read them carefully before beginning any journey.
            </p>
          </CardContent>
        </Card>

        <div className="prose max-w-none text-earth-800 space-y-8">
          <section className="group">
            <div className={cn("flex items-start gap-4 p-5 rounded-lg transition-all", 
                              "hover:bg-spirit-50/50 hover:border-spirit-200")}>
              <div className="bg-spirit-100 text-spirit-700 p-3 rounded-full h-12 w-12 flex items-center justify-center shrink-0">
                <Info size={24} />
              </div>
              <div>
                <h2 className="text-2xl font-semibold mb-3 text-earth-800 group-hover:text-spirit-800 transition-colors">Purpose of the Platform</h2>
                <p>
                  Flow 83 offers AI-guided personal growth journeys designed to support emotional clarity, mindset development, and spiritual or self-awareness expansion. The platform provides structured, daily reflections and exercises based on each user's selected path.
                </p>
              </div>
            </div>
          </section>

          <section className="group">
            <div className={cn("flex items-start gap-4 p-5 rounded-lg transition-all", 
                              "hover:bg-spirit-50/50 hover:border-spirit-200")}>
              <div className="bg-spirit-100 text-spirit-700 p-3 rounded-full h-12 w-12 flex items-center justify-center shrink-0">
                <Bot size={24} />
              </div>
              <div>
                <h2 className="text-2xl font-semibold mb-3 text-earth-800 group-hover:text-spirit-800 transition-colors">AI-Based Guidance</h2>
                <p>
                  All feedback, guidance, and conversational responses on Flow 83 are generated by an artificial intelligence system. While the system is built to simulate emotionally supportive communication, it is not operated by a licensed therapist, coach, or mental health professional.
                </p>
              </div>
            </div>
          </section>

          <section className="group">
            <div className={cn("flex items-start gap-4 p-5 rounded-lg transition-all", 
                              "hover:bg-spirit-50/50 hover:border-spirit-200")}>
              <div className="bg-spirit-100 text-spirit-700 p-3 rounded-full h-12 w-12 flex items-center justify-center shrink-0">
                <ShieldOff size={24} />
              </div>
              <div>
                <h2 className="text-2xl font-semibold mb-3 text-earth-800 group-hover:text-spirit-800 transition-colors">No Guarantee of Results</h2>
                <p>
                  Every individual's experience is unique. Flow 83 makes no promises regarding specific results, personal breakthroughs, or emotional or spiritual outcomes. Results may vary based on personal context, engagement, and interpretation.
                </p>
              </div>
            </div>
          </section>

          <section className="group">
            <div className={cn("flex items-start gap-4 p-5 rounded-lg transition-all", 
                              "hover:bg-spirit-50/50 hover:border-spirit-200")}>
              <div className="bg-spirit-100 text-spirit-700 p-3 rounded-full h-12 w-12 flex items-center justify-center shrink-0">
                <Hospital size={24} />
              </div>
              <div>
                <h2 className="text-2xl font-semibold mb-3 text-earth-800 group-hover:text-spirit-800 transition-colors">Not a Substitute for Professional Help</h2>
                <p>
                  The platform is not a medical, psychological, or therapeutic service. It is not intended to diagnose, treat, or replace mental health services or professional coaching. If you are in emotional distress or crisis, please seek support from a licensed professional or local emergency services.
                </p>
              </div>
            </div>
          </section>

          <section className="group">
            <div className={cn("flex items-start gap-4 p-5 rounded-lg transition-all", 
                              "hover:bg-spirit-50/50 hover:border-spirit-200")}>
              <div className="bg-spirit-100 text-spirit-700 p-3 rounded-full h-12 w-12 flex items-center justify-center shrink-0">
                <User size={24} />
              </div>
              <div>
                <h2 className="text-2xl font-semibold mb-3 text-earth-800 group-hover:text-spirit-800 transition-colors">Personal Responsibility</h2>
                <p>
                  By using Flow 83, you accept full responsibility for your actions, emotional responses, and decisions made during or following your engagement with the platform. You understand that your use of the platform is entirely voluntary and at your own discretion.
                </p>
              </div>
            </div>
          </section>

          <section className="group">
            <div className={cn("flex items-start gap-4 p-5 rounded-lg transition-all", 
                              "hover:bg-spirit-50/50 hover:border-spirit-200")}>
              <div className="bg-spirit-100 text-spirit-700 p-3 rounded-full h-12 w-12 flex items-center justify-center shrink-0">
                <Shield size={24} />
              </div>
              <div>
                <h2 className="text-2xl font-semibold mb-3 text-earth-800 group-hover:text-spirit-800 transition-colors">Privacy & Data Usage</h2>
                <p>
                  We value your privacy. By using Flow 83, you consent to the storage and processing of your responses and interactions with the AI to personalize and improve your experience. Your data will never be sold or shared with third parties without your consent.
                </p>
              </div>
            </div>
          </section>

          <section className="group">
            <div className={cn("flex items-start gap-4 p-5 rounded-lg transition-all", 
                              "hover:bg-spirit-50/50 hover:border-spirit-200")}>
              <div className="bg-spirit-100 text-spirit-700 p-3 rounded-full h-12 w-12 flex items-center justify-center shrink-0">
                <Copyright size={24} />
              </div>
              <div>
                <h2 className="text-2xl font-semibold mb-3 text-earth-800 group-hover:text-spirit-800 transition-colors">Intellectual Property</h2>
                <p>
                  All content, methods, user journeys, visuals, and AI logic on Flow 83 are the exclusive property of the platform and its creators. No content may be reproduced, copied, distributed, or used for commercial purposes without prior written permission.
                </p>
              </div>
            </div>
          </section>

          <section className="group">
            <div className={cn("flex items-start gap-4 p-5 rounded-lg transition-all", 
                              "hover:bg-spirit-50/50 hover:border-spirit-200")}>
              <div className="bg-spirit-100 text-spirit-700 p-3 rounded-full h-12 w-12 flex items-center justify-center shrink-0">
                <FileText size={24} />
              </div>
              <div>
                <h2 className="text-2xl font-semibold mb-3 text-earth-800 group-hover:text-spirit-800 transition-colors">Age Restriction</h2>
                <p>
                  This platform is intended for users who are 18 years of age or older. By accessing or using Flow 83, you confirm that you meet this age requirement.
                </p>
              </div>
            </div>
          </section>

          <section className="group">
            <div className={cn("flex items-start gap-4 p-5 rounded-lg transition-all", 
                              "hover:bg-spirit-50/50 hover:border-spirit-200")}>
              <div className="bg-spirit-100 text-spirit-700 p-3 rounded-full h-12 w-12 flex items-center justify-center shrink-0">
                <Ban size={24} />
              </div>
              <div>
                <h2 className="text-2xl font-semibold mb-3 text-earth-800 group-hover:text-spirit-800 transition-colors">Cancellation & Refund Policy</h2>
                <p>
                  Due to the digital and personalized nature of our content, all purchases are final and non-refundable. If you experience a technical issue or require support, please contact us directly.
                </p>
              </div>
            </div>
          </section>

          <section className="group">
            <div className={cn("flex items-start gap-4 p-5 rounded-lg transition-all", 
                              "hover:bg-spirit-50/50 hover:border-spirit-200")}>
              <div className="bg-spirit-100 text-spirit-700 p-3 rounded-full h-12 w-12 flex items-center justify-center shrink-0">
                <RefreshCw size={24} />
              </div>
              <div>
                <h2 className="text-2xl font-semibold mb-3 text-earth-800 group-hover:text-spirit-800 transition-colors">Platform Availability & Changes</h2>
                <p>
                  Flow 83 reserves the right to update, change, or discontinue any part of the platform, including features, services, or user journeys, at any time without prior notice.
                </p>
              </div>
            </div>
          </section>

          <section className="group">
            <div className={cn("flex items-start gap-4 p-5 rounded-lg transition-all", 
                              "hover:bg-spirit-50/50 hover:border-spirit-200")}>
              <div className="bg-spirit-100 text-spirit-700 p-3 rounded-full h-12 w-12 flex items-center justify-center shrink-0">
                <Settings size={24} />
              </div>
              <div>
                <h2 className="text-2xl font-semibold mb-3 text-earth-800 group-hover:text-spirit-800 transition-colors">User Conduct</h2>
                <p>
                  Users are expected to engage respectfully and ethically with the platform. Any attempt to abuse, exploit, or manipulate the system — including spamming, offensive language, or disrupting the AI — may result in restricted access or account suspension.
                </p>
              </div>
            </div>
          </section>

          <section className="group">
            <div className={cn("flex items-start gap-4 p-5 rounded-lg transition-all", 
                              "hover:bg-spirit-50/50 hover:border-spirit-200")}>
              <div className="bg-spirit-100 text-spirit-700 p-3 rounded-full h-12 w-12 flex items-center justify-center shrink-0">
                <Mail size={24} />
              </div>
              <div>
                <h2 className="text-2xl font-semibold mb-3 text-earth-800 group-hover:text-spirit-800 transition-colors">Contact</h2>
                <p>
                  If you have questions, feedback, or need support regarding these terms, you may contact us at:
                  <a href="/contact" className="text-spirit-600 hover:text-spirit-800 ml-1 transition-colors">our Contact page</a>.
                </p>
              </div>
            </div>
          </section>
          
          <section className="mt-12 border-t border-earth-200 pt-8">
            <div className="p-5">
              <p className="font-semibold text-center text-earth-800">
                By continuing to use Flow 83, you acknowledge that you have read, understood, and agreed to these Terms.
              </p>
            </div>
          </section>
        </div>
      </div>
    </div>
  );
};

export default TermsAndConditions;
